name: Web testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: choice
        options:
          - PROD

jobs:
  build-and-test:
    name: Build and Test on GitHub Runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Docker Compose
        run: |
          echo "Running tests for Ikea"
          echo "Environment: ${{ github.event.inputs.environment }}"
          docker compose up -d
          docker compose run --rm testframework -s tests/web/ikea/test_ikea.py --env ${{ github.event.inputs.environment }}
          docker compose down