name: Web testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        type: choice
        options:
          - PROD

jobs:
  build-and-test:
    name: Build and Test on GitHub Runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variable
        run: echo "ENVIRONMENT=${{ github.event.inputs.environment || 'PROD' }}" >> $GITHUB_ENV

      - name: Build and run tests with Docker Compose
        run: |
          echo "Running tests for Ikea"
          echo "Environment: $ENVIRONMENT"
          docker compose run --rm testframework -s tests/web/ikea/test_ikea.py --env $ENVIRONMENT
          docker compose down
